### ISSUE TITLE
Embla að lesa eldgamlar fréttir.

### ISSUE THREAD

**Issue by userdeadinterface** [mideind/GreynirServer#205]
Embla er að lesa nákvæmlega sömu fréttir. Ein af fréttunum er þessi frétt hér: https://www.ruv.is/frett/2022/12/03/leit-heldur-afram-ad-sjomanni-sem-fell-utbyrdis. Ég er að nota Emblu á Android-síma, ef það breytir einhverju.

![Screenshot_2023-01-13-17-01-59-77_dc819d48923d09bbb0b5635e11438141](https://user-images.githubusercontent.com/88093623/212377239-ec488c53-14d9-4755-8d5a-0e9b6965b3d3.jpg)

**Comment by sultur** [comment]
Takk fyrir að benda á þetta! Nýji vefur RÚV bíður ekki upp á endapunktinn sem Embla notaði (og þessi endapunktur hætti greinilega að uppfærast í desember), en við munum vinna í þessu um leið og tími gefst.
